version: '3.8'

services:

  mongo:
    image: mongo:latest
    container_name: book-library-tool_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - ./docker/seed/init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh
      - ./docker/seed/bookLibraryTool.books.json:/docker-entrypoint-initdb.d/bookLibraryTool.books.json
    ports:
      - 27017:27017
    restart: unless-stopped
